# Generated by Django 5.2.14 on 2026-05-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="starting_balance",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="starting_balance_as_of",
            field=models.DateField(blank=True, null=True),
        ),
    ]
