# Generated by Django 5.2.14 on 2026-05-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_starting_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="starting_balance",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="starting_balance_as_of",
        ),
    ]
