# Generated by Django 5.2.14 on 2026-05-09 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pockets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=8,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("briefcase", "Briefcase"),
                            ("trending-up", "Trending up"),
                            ("gift", "Gift"),
                            ("rotate-cw", "Refund"),
                            ("sparkles", "Sparkles"),
                            ("utensils", "Food"),
                            ("shopping-cart", "Groceries"),
                            ("car", "Transport"),
                            ("zap", "Utilities"),
                            ("home", "Home"),
                            ("activity", "Health"),
                            ("popcorn", "Entertainment"),
                            ("shopping-bag", "Shopping"),
                            ("ellipsis", "Other"),
                        ],
                        default="ellipsis",
                        max_length=40,
                    ),
                ),
                (
                    "color_token",
                    models.CharField(
                        choices=[
                            ("brand-200", "Sand"),
                            ("brand-300", "Wheat"),
                            ("brand-400", "Tan"),
                            ("brand-500", "Caramel"),
                            ("brand-600", "Toffee"),
                            ("brand-700", "Mocha"),
                        ],
                        default="brand-400",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=8,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=14)),
                ("occurred_on", models.DateField()),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="transactions.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pocket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="pockets.pocket",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_on", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=14)),
                ("occurred_on", models.DateField()),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_pocket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="pockets.pocket",
                    ),
                ),
                (
                    "to_pocket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="pockets.pocket",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_on", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("created_by", "name", "kind"),
                name="category_unique_name_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["pocket", "-occurred_on"], name="transaction_pocket__15a370_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category", "-occurred_on"],
                name="transaction_categor_bea1c0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="txn_amount_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["from_pocket", "-occurred_on"],
                name="transaction_from_po_606175_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["to_pocket", "-occurred_on"],
                name="transaction_to_pock_bfd9a0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="transfer_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_pocket", models.F("to_pocket")), _negated=True
                ),
                name="transfer_pockets_distinct",
            ),
        ),
    ]
