# Generated by Django 5.2.14 on 2026-05-22 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=8,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("briefcase", "Briefcase"),
                            ("trending-up", "Trending up"),
                            ("gift", "Gift"),
                            ("rotate-cw", "Refund"),
                            ("sparkles", "Sparkles"),
                            ("utensils", "Food"),
                            ("shopping-cart", "Groceries"),
                            ("car", "Transport"),
                            ("zap", "Utilities"),
                            ("home", "Home"),
                            ("activity", "Health"),
                            ("popcorn", "Entertainment"),
                            ("shopping-bag", "Shopping"),
                            ("ellipsis", "Other"),
                        ],
                        default="ellipsis",
                        max_length=40,
                    ),
                ),
                (
                    "color_token",
                    models.CharField(
                        choices=[
                            ("brand-200", "Sand"),
                            ("brand-300", "Wheat"),
                            ("brand-400", "Tan"),
                            ("brand-500", "Caramel"),
                            ("brand-600", "Toffee"),
                            ("brand-700", "Mocha"),
                        ],
                        default="brand-400",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("wallet", "Wallet"),
                            ("banknote", "Cash"),
                            ("coins", "Coins"),
                            ("credit-card", "Card"),
                            ("landmark", "Bank"),
                            ("smartphone", "E-wallet"),
                            ("building-2", "Institution"),
                            ("piggy-bank", "Savings"),
                            ("ellipsis", "Other"),
                        ],
                        default="wallet",
                        max_length=40,
                    ),
                ),
                (
                    "color_token",
                    models.CharField(
                        choices=[
                            ("brand-200", "Sand"),
                            ("brand-300", "Wheat"),
                            ("brand-400", "Tan"),
                            ("brand-500", "Caramel"),
                            ("brand-600", "Toffee"),
                            ("brand-700", "Mocha"),
                        ],
                        default="brand-500",
                        max_length=20,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="ledger.household",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=8,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=14)),
                ("occurred_on", models.DateField()),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="transactions.category",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recurring_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="ledger.recurringrule",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transactions.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_on", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("created_by", "name", "kind"),
                name="category_unique_name_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                fields=("household", "name"), name="source_unique_name_per_household"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["owner", "-occurred_on"], name="transaction_owner_i_4e5bd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category", "-occurred_on"],
                name="transaction_categor_bea1c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["source", "-occurred_on"], name="transaction_source__f96cbf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="txn_amount_positive"
            ),
        ),
    ]
