# Generated by Django 5.2.14 on 2026-05-24 10:21
#
# Hand-ordered for SQLite: drop the source index BEFORE removing
# Transaction.source (SQLite remakes the table from model state, which would
# otherwise still reference the dropped field), and DeleteModel(Source) drops
# the source table wholesale — taking its `household` field and unique
# constraint with it, so they need no separate RemoveField/RemoveConstraint.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_remove_recurringrule_source_and_more"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_source__f96cbf_idx",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="source",
        ),
        migrations.DeleteModel(
            name="Source",
        ),
    ]
