# Generated by Django 5.2.14 on 2026-05-09 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pockets", "0002_pocketshare"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=8,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=14)),
                ("notes", models.CharField(blank=True, max_length=500)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=8,
                    ),
                ),
                ("interval", models.PositiveSmallIntegerField(default=1)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("occurrences", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_rules",
                        to="transactions.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_rules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pocket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_rules",
                        to="pockets.pocket",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="recurring_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="transactions.recurringrule",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringrule",
            index=models.Index(
                fields=["pocket", "is_active"], name="transaction_pocket__8af4e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringrule",
            index=models.Index(
                fields=["created_by", "is_active"],
                name="transaction_created_b35f6c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="recurring_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval__gte", 1)), name="recurring_interval_min1"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", False),
                    ("occurrences__isnull", False),
                    _connector="OR",
                ),
                name="recurring_bounded",
            ),
        ),
    ]
