# Generated by Django 5.2.14 on 2026-05-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0002_remove_source_household_remove_transaction_source_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
