# Generated by Django 5.2.14 on 2026-05-10 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pockets", "0003_credit_cards"),
        ("transactions", "0003_remove_recurring"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="installment_group",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="installment_index",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="installment_total",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("installment_group__isnull", True),
                        ("installment_index__isnull", True),
                        ("installment_total__isnull", True),
                    ),
                    models.Q(
                        ("installment_group__isnull", False),
                        ("installment_index__gte", 1),
                        ("installment_total__gte", 2),
                        ("installment_total__lte", 36),
                    ),
                    _connector="OR",
                ),
                name="txn_installment_consistent",
            ),
        ),
    ]
