# Generated by Django 5.2.14 on 2026-05-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringrule",
            name="source",
        ),
        migrations.DeleteModel(
            name="DailyBalanceSnapshot",
        ),
    ]
