# Generated by Django 5.2.14 on 2026-05-24 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_head(apps, schema_editor):
    """Each existing household's head defaults to its earliest member."""
    Household = apps.get_model("ledger", "Household")
    HouseholdMember = apps.get_model("ledger", "HouseholdMember")
    for hh in Household.objects.all():
        first = (
            HouseholdMember.objects.filter(household=hh)
            .order_by("created_at", "id")
            .first()
        )
        if first and hh.head_id is None:
            hh.head_id = first.user_id
            hh.save(update_fields=["head"])


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_remove_recurringrule_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_households",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_head, migrations.RunPython.noop),
    ]
