# Generated by Django 5.2.14 on 2026-05-09 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pocket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("is_main", models.BooleanField(default=False)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("wallet", "Wallet"),
                            ("piggy-bank", "Piggy bank"),
                            ("banknote", "Banknote"),
                            ("credit-card", "Credit card"),
                            ("landmark", "Bank"),
                            ("coins", "Coins"),
                            ("gem", "Gem"),
                            ("shopping-bag", "Shopping"),
                            ("home", "Home"),
                            ("heart", "Heart"),
                            ("plane", "Travel"),
                            ("car", "Vehicle"),
                            ("graduation-cap", "Education"),
                            ("activity", "Health"),
                        ],
                        default="wallet",
                        max_length=40,
                    ),
                ),
                (
                    "color_token",
                    models.CharField(
                        choices=[
                            ("brand-200", "Sand"),
                            ("brand-300", "Wheat"),
                            ("brand-400", "Tan"),
                            ("brand-500", "Caramel"),
                            ("brand-600", "Toffee"),
                            ("brand-700", "Mocha"),
                        ],
                        default="brand-500",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pockets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="pockets.pocket",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_main", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "parent", "name"),
                        name="pocket_unique_name_within_parent",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_main", True)),
                        fields=("owner",),
                        name="pocket_one_main_per_owner",
                    ),
                ],
            },
        ),
    ]
