# Generated by Django 5.2.14 on 2026-05-10 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pockets", "0002_pocketshare"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pocket",
            name="due_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pocket",
            name="kind",
            field=models.CharField(
                choices=[("cash", "Cash"), ("credit", "Credit card")],
                default="cash",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="pocket",
            name="statement_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="pocket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("due_day__isnull", True),
                        ("kind", "cash"),
                        ("statement_day__isnull", True),
                    ),
                    models.Q(
                        ("due_day__gte", 1),
                        ("due_day__lte", 28),
                        ("kind", "credit"),
                        ("statement_day__gte", 1),
                        ("statement_day__lte", 28),
                    ),
                    _connector="OR",
                ),
                name="pocket_credit_cycle_days",
            ),
        ),
        migrations.AddConstraint(
            model_name="pocket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_main", False), ("kind", "cash"), _connector="OR"
                ),
                name="pocket_main_is_cash",
            ),
        ),
    ]
